
INSERT INTO salesforce.Custodians (name, phone, billing_street, billing_city, billing_state, billing_zip, salesforce_id) VALUES  
('Chase', '3125551234','123 chase st', 'Chase', 'CT', '12345', 'sfIdChase1'), 
('Wells Fargo', '5204444444','123 wells st', 'Fargo', 'ND', '12444', 'sfIDWF1'), 
('Sun America','(800) 858-8850', '330 W 9th St.', 'Kansas City', 'MO',	'64105' , '0013000001FB3JmAAL'
),
('Millennium Trust', '(877) 682-4727 Opt. 1, 1', '2001 Spring Rd, Ste 700', 'Oak Brook', 'IL', '60523',	'0013000000VK0aqAAD'),
('Pershing' ,'(201) 413-2323 Option 2', 'One Pershing Plaza','Jersey City', 'NJ', '73999', '0013000000T8ZcSAAV'
),
('Board of Pensions Evangelica Lutheran Church', '507-555-5555', '800 Marquette Ave','Minneapolis','MN','55057','0013000000T8sNnAAJ');